Repository SouJunior/mentores-backend, pull requests merged in 2023-04, with the labels that each got.

#1 initial commit
  .editorconfig
  .env.example
  .eslintrc.js
  .gitignore
  .prettierrc
  README.md
  nest-cli.json
  package-lock.json
  package.json
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/main.ts
  tsconfig.build.json
  tsconfig.json
Labels: enhancement

#2 Configs
  .github/workflows/docker-image.yml
  .github/workflows/renovate.yml
  Dockerfile
  docker-compose.yml
  package-lock.json
  package.json
  renovate.json
  src/app.controller.ts
  src/app.service.ts
  test/app.service.spec.ts
  tsconfig.build.json
  tsconfig.json
Labels: documentation

#3 Swagger
  .env.example
  package-lock.json
  package.json
  src/app.module.ts
  src/main.ts
Labels: documentation, enhancement

#4 implementação typeorm
  package-lock.json
  package.json
  src/app.module.ts
Labels: enhancement

#7 create user and login
  .github/workflows/renovate.yml
  package-lock.json
  package.json
  src/app.module.ts
  src/database/entities/user.entity.ts
  src/main.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/decorator/logged-user.decorator.ts
  src/modules/auth/dtos/user-login.dto.ts
  src/modules/auth/jtw/jwt.strategy.ts
  src/modules/user/decorators/email-not-registered.decorator.ts
  src/modules/user/decorators/match.decorator.ts
  src/modules/user/dtos/create-user.dto.ts
  src/modules/user/dtos/get-by-param.dto.ts
  src/modules/user/dtos/update-user.dto.ts
  src/modules/user/repository/user.repository.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.module.ts
  src/modules/user/user.service.ts
  src/shared/Swagger/bad-request.swagger.ts
  src/shared/Swagger/not-found.swagger.ts
  src/shared/Swagger/unauthorized.swagger.ts
  src/shared/Swagger/unprocessable-entity.swagger.ts
  src/shared/Swagger/user/create-response.swagger.ts
  src/shared/Swagger/user/list-response.swagger.ts
  src/shared/enums/status.enum.ts
  src/shared/pagination/index.ts
  src/shared/pagination/order.dto.ts
  src/shared/pagination/page.dto.ts
  src/shared/pagination/pageMeta.dto.ts
  src/shared/pagination/pageMetaParameters.dto.ts
  src/shared/pagination/pageOptions.dto.ts
  src/shared/pipes/pipe-entity.pipe.ts
  src/shared/utils/handle-error.util.ts
Labels: documentation, enhancement

#5 feat: inicio crud de usuarios
  .github/workflows/renovate.yml
  shared/pagination/index.ts
  shared/pagination/order.dto.ts
  shared/pagination/page.dto.ts
  shared/pagination/pageMeta.dto.ts
  shared/pagination/pageMetaParameters.dto.ts
  shared/pagination/pageOptions.dto.ts
  shared/utils/handle-error.util.ts
  src/app.module.ts
  src/database/entities/user.entity.ts
  src/modules/user/repository/user.repository.ts
  src/modules/user/user.controller.spec.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.module.ts
  src/modules/user/user.service.spec.ts
  src/modules/user/user.service.ts
Labels: enhancement
